[build]
  command = "npm install -g staticrypt && npm run build:production"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.7"
  GO_VERSION = "1.22.2"
  STATICRYPT_PASSWORD = "@Samples26!"

[context.production]
  command = "npm install -g staticrypt && npm run build:production"
