[build]
  command = "npm run build:production"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.7"
GO_VERSION = "1.22.2"
ENABLE_ENCRYPT = "0"

[context.production]
  command = "npm run build:production"

[[redirects]]
  from = "/pdfs/*"
  to = "/pdfs/pdfs/:splat"
  status = 200
  force = true
