  mv ./public/docs/writing_samples/style_guide/index_encrypted.html ./public/docs/writing_samples/style_guide/index.html
  echo $PASSWORD | staticrypt ./public/docs/writing_samples/technical_guides/index.html -m "Enter the password to view this page." --stdin
  mv ./public/docs/writing_samples/technical_guides/index_encrypted.html ./public/docs/writing_samples/technical_guides/index.html
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    HUGO_VERSION: 0.126.0
    GITHUB_PAGES: true
    PASSWORD: ***
node:fs:1688
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat './public/docs/writing_samples/index.html'
    at Object.statSync (node:fs:1688:3)
    at /usr/local/lib/node_modules/staticrypt/cli/index.js:101:76
    at Array.filter (<anonymous>)
    at runStatiCrypt (/usr/local/lib/node_modules/staticrypt/cli/index.js:101:56) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: './public/docs/writing_samples/_index.html'
}

Node.js v18.20.3
Enter your long, unusual password: 
Error: Process completed with exit code 1.